apiVersion: v1
kind: Service
metadata:
    name: {{ include "fed.fullname" . }}
    labels:
        app.kubernetes.io/name: {{ include "fed.name" . }}
        helm.sh/chart: {{ include "fed.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
    type: {{ .Values.service.type }}
    ports:
        - port: {{ .Values.service.ports.port }}
          nodePort: {{ .Values.service.ports.nodePort }}
          targetPort: {{ .Values.service.ports.port }}
          protocol: TCP
          name: http
    selector:
        app.kubernetes.io/name: {{ include "fed.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
